version: "3.8"

services:

  # ------------------------
  # MySQL Database
  # ------------------------
  db:
    image: mysql:8
    container_name: bankify-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bankify
      MYSQL_USER: bankify
      MYSQL_PASSWORD: bankify
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - bankify-net

  # ------------------------
  # Logger (.NET + Serilog)
  # ------------------------
  logger:
    build: ./Logger/BankifyLogger
    container_name: bankify-logger
    restart: always
    environment:
      ASPNETCORE_URLS: http://+:5000
    ports:
      - "5000:5000"
    volumes:
      - ./logger-logs:/app/logs
    networks:
      - bankify-net

  # ------------------------
  # Spring Boot Backend
  # ------------------------
  backend:
    build: ./Server/Bankify
    container_name: bankify-backend
    restart: always
    depends_on:
      - db
      - logger
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/bankify
      SPRING_DATASOURCE_USERNAME: bankify
      SPRING_DATASOURCE_PASSWORD: bankify

      # Logger service URL
      LOGGER_SERVICE_URL: http://logger:5000/api/logs
    ports:
      - "8080:8080"
    networks:
      - bankify-net

  # ------------------------
  # React Frontend
  # ------------------------
  frontend:
    build:
      context: ./Client/app
      args:
        # React -> Spring Boot
        VITE_API_BASE_URL: http://localhost:8080/bankify  

        # React -> Logger
        VITE_LOGGER_BASE_URL: http://localhost:5000
    container_name: bankify-frontend
    restart: always
    depends_on:
      - backend
      - logger
    ports:
      - "5173:80"
    networks:
      - bankify-net

# ------------------------
# Persistent Volumes
# ------------------------
volumes:
  db_data:

# ------------------------
# Network
# ------------------------
networks:
  bankify-net:
    driver: bridge
